name: build all RPMs
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fedora
      env:
        shell: bash
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: dnf install -y curl rpmdevtools rpm-build dnf-utils rubygems

    - name: Download RPMs
      run: |
        rpmdev-setuptree
        for i in ./*.spec
        do
        spectool -R -g $i &
        done
        wait

    - name: Build gtk3-ubuntu
      run: |
        curl "https://src.fedoraproject.org/rpms/gtk3/raw/f$(rpm --eval '%{?fedora}')/f/gtk3.spec" -o ./gtk3.spec
        patch -p1 ./gtk3.spec ./patches/gtk3-ubuntu.patch
        dnf builddep -y --spec ./gtk3.spec
        spectool -R -g ./gtk3.spec
        rpmbuild --nodebuginfo -bb ./gtk3.spec
        rm -f "$(rpm --eval '%{_rpmdir}')"/x86_64/gtk3-ubuntu-tests* "$(rpm --eval '%{_rpmdir}')"/x86_64/gtk3-ubuntu-devel-docs* "$(rpm --eval '%{_rpmdir}')"/x86_64/gtk-update-icon-cache* "$(rpm --eval '%{_rpmdir}')"/x86_64/gtk3-ubuntu-immodule*
        dnf install -y "$(rpm --eval '%{_rpmdir}')"/x86_64/gtk3-ubuntu*

    - name: Build xpathselect-devel
      run: |
        dnf builddep -y --spec ./xpathselect-devel.spec
        rpmbuild --nodebuginfo -bb ./xpathselect-devel.spec

    - name: Build libunity
      run: |
        dnf builddep -y --spec ./libunity.spec
        rpmbuild --nodebuginfo -bb ./libunity.spec

    - name: Build libunity-misc-devel
      run: |
        dnf builddep -y --spec ./libunity-misc-devel.spec
        rpmbuild --nodebuginfo -bb ./libunity-misc-devel.spec

    - name: Build compiz9
      run: |
        dnf builddep -y --spec ./compiz9.spec
        rpmbuild --nodebuginfo -bb ./compiz9.spec

    - name: Build frame-devel
      run: |
        dnf builddep -y --spec ./frame-devel.spec
        rpmbuild --nodebuginfo -bb ./frame-devel.spec

    - name: Build grail-devel
      run: |
        rpm -ivh "$(rpm --eval '%{_rpmdir}')"/x86_64/frame-devel*
        dnf builddep -y --spec ./grail-devel.spec
        rpmbuild --nodebuginfo -bb ./grail-devel.spec

    - name: Build geis-devel
      run: |
        rpm -ivh "$(rpm --eval '%{_rpmdir}')"/x86_64/grail-devel*
        dnf builddep -y --spec ./geis-devel.spec
        rpmbuild --nodebuginfo -bb ./geis-devel.spec

    - name: Build glewmx-devel
      run: |
        dnf builddep -y --spec ./glewmx-devel.spec
        rpmbuild --nodebuginfo -bb ./glewmx-devel.spec

    - name: Build nux-devel
      run: |
        rpm -ivh "$(rpm --eval '%{_rpmdir}')"/x86_64/geis-devel* "$(rpm --eval '%{_rpmdir}')"/x86_64/glewmx-devel*
        dnf builddep -y --spec ./nux-devel.spec
        rpmbuild --nodebuginfo -bb ./nux-devel.spec

    - name: Build gsettings-ubuntu-touch-schemas-devel
      run: |
        dnf builddep -y --spec ./gsettings-ubuntu-touch-schemas-devel.spec
        rpmbuild --nodebuginfo -bb ./gsettings-ubuntu-touch-schemas-devel.spec

    - name: Build unity-settings-daemon-devel
      run: |
        rpm -ivh "$(rpm --eval '%{_rpmdir}')"/x86_64/gsettings-ubuntu-touch-schemas-devel*
        dnf builddep -y --spec ./unity-settings-daemon-devel.spec
        rpmbuild --nodebuginfo -bb ./unity-settings-daemon-devel.spec

    - name: Build ido-devel
      run: |
        dnf builddep -y --spec ./ido-devel.spec
        rpmbuild --nodebuginfo -bb ./ido-devel.spec

    - name: Build libindicator
      run: |
        curl "https://src.fedoraproject.org/rpms/libindicator/raw/f$(rpm --eval '%{?fedora}')/f/libindicator.spec" -o ./libindicator.spec
        patch -p1 ./libindicator.spec ./patches/libindicator-16.10.0.patch
        dnf builddep -y --spec ./libindicator.spec
        rpmbuild --nodebuginfo -bb ./libindicator.spec

    - name: Build unity-shell
      run: |
        dnf install -y "$(rpm --eval '%{_rpmdir}')"/*/*.rpm
        dnf builddep -y --spec ./unity-shell.spec
        rpmbuild --nodebuginfo -bb ./unity-shell.spec

    - name: Build unity-session
      run: |
        rpm -ivh "$(rpm --eval '%{_rpmdir}')"/*/unity-shell*.rpm
        dnf builddep -y --spec ./unity-session.spec
        rpmbuild --nodebuginfo -bb ./unity-session.spec

    - name: Build unity-asset-pool
      run: |
        dnf builddep -y --spec ./unity-asset-pool.spec
        rpmbuild --nodebuginfo -bb ./unity-asset-pool.spec

    - name: Upload RPMs
      if: success() || failure()
      uses: actions/upload-artifact@v3.1.0
      with:
          name: Built-RPMS
          path: ~/rpmbuild/RPMS/*/*
